name: GitHub Classroom Workflow
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install the necessary packages
        run: pip3.10 install -r requirements.txt

      - name: Run unit tests for Rating service
        run: pytest -vs src/rating_service/app/unit_tests/rating.py

      - name: Run unit tests for Reservation service
        run: pytest -vs src/reservation_service/app/unit_tests/reservation.py -W ignore::DeprecationWarning

  deploy:
    name: Deploy service on VM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Copy code to VM
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "v4,scripts,Makefile,src,docker,db_sql,docker-compose.yml,config.yaml,requirements.txt"
          target: /home/${{ secrets.SSH_USERNAME }}/library_system_lab03

      - name: Run app on VM
        uses: appleboy/ssh-action@v1.0.0
        env:
          WAIT_PORTS: 8080,8070,8060,8050
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
             cd /home/${{ secrets.SSH_USERNAME }}/library_system_lab03
             sudo -S docker compose down
             sudo -S docker rmi gateway_service_lab03
             sudo -S docker rmi library_service_lab03
             sudo -S docker rmi reservation_service_lab03
             sudo -S docker rmi rating_service_lab03
             sudo -S docker compose up -d
             sudo ./scripts/wait-script.sh

  autograding:
    name: Autograding
    needs: [deploy]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: appleboy/ssh-action@v1.0.0
        timeout-minutes: 10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/${{ secrets.SSH_USERNAME }}/library_system_lab03
            echo ${{ secrets.SSH_PASSWORD }} | sudo ./scripts/test-script.sh v4 rating_service_lab03 8050
